<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="differential_drive_robot">
  <xacro:property name="wheel_separation" value="0.070" />
  <xacro:arg name="robot_color" default="Red" />
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="wheel_width" value="0.03" />
  <xacro:property name="body_height" value="0.05" />
  <xacro:property name="body_width" value="0.15" />
  <xacro:property name="body_length" value="0.25" />

  <!-- <material name="black">
  <ambient/>
    <color rgba="0 0 0 1"/>
  </material> -->

  <gazebo reference="base_link">
    <material>Gazebo/$(arg robot_color)</material>

    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
  </gazebo>

  <gazebo reference="wheelRF">
    <material>Gazebo/Black</material>
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
  </gazebo>
  <gazebo reference="wheelRB">
    <material>Gazebo/Black</material>
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
  </gazebo>
  <gazebo reference="wheelLB">
    <material>Gazebo/Black</material>
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
  </gazebo>
  <gazebo reference="wheelLF">
    <material>Gazebo/Black</material>
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
  </gazebo>
<!-- 
  <gazebo reference="wheelLF">
    <material>Gazebo/Blue</material>
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
  </gazebo> -->

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>      
    </visual>

    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry> 
    </collision>

    <inertial>
      <mass value="0.18"/>
      <inertia ixx="6.0e-4" ixy="0" ixz="0" iyy="6.0e-4" iyz="0" izz="6.0e-4"/>
    </inertial>
  </link>

  <link name="wheelLF">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.03"/>
      <inertia ixx="1.75e-5" ixy="0.0" ixz="0.0" iyy="1.75e-5" iyz="0.0" izz="1.75e-5"/>
    </inertial>
  </link>

  <link name="wheelLB">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.03"/>
      <inertia ixx="1.75e-5" ixy="0.0" ixz="0.0" iyy="1.75e-5" iyz="0.0" izz="1.75e-5"/>
    </inertial>
  </link>

  <link name="wheelRF">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.03"/>
      <inertia ixx="1.75e-5" ixy="0.0" ixz="0.0" iyy="1.75e-5" iyz="0.0" izz="1.75e-5"/>
    </inertial>  
  </link>

  <link name="wheelRB">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.03"/>
      <inertia ixx="1.75e-5" ixy="0.0" ixz="0.0" iyy="1.75e-5" iyz="0.0" izz="1.75e-5"/>
    </inertial>  
  </link>

  <joint name="jointLF" type="continuous">
    <parent link="base_link"/>
    <child link="wheelLF"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${body_width/2} ${body_width/2 + wheel_width/2} -${body_height/2 - 0.01}" rpy="${pi/2} 0 0" /> 
    <dynamics friction="0.1"/>
  </joint>

  <joint name="jointLB" type="continuous">
    <parent link="base_link"/>
    <child link="wheelLB"/>
    <axis xyz="0 0 1"/>
    <origin xyz="-${body_width/2} ${body_width/2 + wheel_width/2} -${body_height/2 - 0.01}" rpy="${pi/2} 0 0" /> 
    <dynamics friction="0.1"/>
  </joint>

  <joint name="jointRF" type="continuous">
    <parent link="base_link"/>
    <child link="wheelRF"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${body_width/2} -${body_width/2 + wheel_width/2} -${body_height/2 - 0.01}" rpy="${pi/2} 0 0" />
    <dynamics friction="0.1"/>
  </joint>

  <joint name="jointRB" type="continuous">
    <parent link="base_link"/>
    <child link="wheelRB"/>
    <axis xyz="0 0 1"/>
    <origin xyz="-${body_width/2} -${body_width/2 + wheel_width/2} -${body_height/2 - 0.01}" rpy="${pi/2} 0 0" />
    <dynamics friction="0.1"/>
  </joint>

  <!-- <gazebo>
    <plugin name="wb_plugin" filename="libwb_plugin.so"> </plugin>
  </gazebo> -->

  <!-- <xacro:include filename="$(find nexus_4wd_mecanum_description)/urdf/nexus_4wd_mecanum.gazebo" /> -->
  
  <gazebo>

    <plugin name="nexus_ros_force_based_move" filename="libnexus_ros_force_based_move.so">
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <odometryRate>25.0</odometryRate>
      <robotBaseFrame>base_link</robotBaseFrame>
      <cmdVelTimeOut>0.25</cmdVelTimeOut>
      <publishOdometryTf>0</publishOdometryTf>
      <yaw_velocity_p_gain>1.0</yaw_velocity_p_gain>
      <x_velocity_p_gain>15.0</x_velocity_p_gain>
      <y_velocity_p_gain>15.0</y_velocity_p_gain>
      <max_x_velocity>0.6</max_x_velocity>
      <max_y_velocity>0.6</max_y_velocity>
      <max_yaw_velocity>0.5</max_yaw_velocity>
    </plugin>
  </gazebo>

  <!-- <gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <robotNamespace>/</robotNamespace>
      <jointName>jointLF</jointName>

      <updateRate>100.0</updateRate>
      <alwaysOn>true</alwaysOn>
    </plugin>
  </gazebo> -->
  
  <!-- hokuyo -->
  <!-- <gazebo reference="base_link">
    <sensor type="gpu_ray" name="head_hokuyo_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.570796</min_angle>
            <max_angle>1.570796</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>

          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_gpu_laser.so">
        <topicName>scan</topicName>
        <frameName>base_link</frameName>
      </plugin>
    </sensor>
  </gazebo> -->

<!-- <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>40</updateRate>
        <legacyMode>false</legacyMode>
        <leftJoint>base_right_wheel_joint</leftJoint>
        <rightJoint>base_left_wheel_joint</rightJoint>
        <wheelSeparation>0.39</wheelSeparation>
        <wheelDiameter>0.15</wheelDiameter>
        <torque>5</torque>
        <commandTopic>cmd_vel</commandTopic>
        <odometryTopic>odom</odometryTopic>
        <odometryFrame>odom</odometryFrame>
        <robotBaseFrame>base_link</robotBaseFrame>
        <publishWheelTF>false</publishWheelTF>
        <publishWheelJointState>false</publishWheelJointState>
        <rosDebugLevel>na</rosDebugLevel>
        <wheelAcceleration>0</wheelAcceleration>
        <wheelTorque>5</wheelTorque>
        <odometrySource>world</odometrySource>
        <publishTf>1</publishTf>
    </plugin>
</gazebo> -->

</robot>